# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestsplit():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testsplit(self):
    # Test name: test_split
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("http://127.0.0.1:5000/")
    # 2 | setWindowSize | 1936x1176 |  | 
    self.driver.set_window_size(1936, 1176)
    # 3 | click | css=a:nth-child(4) > h2 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4) > h2").click()
    # 4 | type | name=phrase | Le Lorem Ipsum est simplement du faux texte employé | 
    self.driver.find_element(By.NAME, "phrase").send_keys("Le Lorem Ipsum est simplement du faux texte employé")
    # 5 | click | css=.text-center:nth-child(6) > .btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(6) > .btn").click()
    # 6 | click | css=div:nth-child(6) h3 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(6) h3").click()
    # 7 | type | name=phrase | Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. | 
    self.driver.find_element(By.NAME, "phrase").send_keys("Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression.")
    # 8 | click | css=.text-center:nth-child(6) > .btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(6) > .btn").click()
    # 9 | click | css=div:nth-child(9) h3 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(9) h3").click()
  
