# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestpine():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testpine(self):
    # Test name: test_pine
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("http://127.0.0.1:5000/")
    # 2 | setWindowSize | 550x691 |  | 
    self.driver.set_window_size(550, 691)
    # 3 | click | css=a:nth-child(1) > h2 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(1) > h2").click()
    # 4 | type | name=nombre | 3 | 
    self.driver.find_element(By.NAME, "nombre").send_keys("3")
    # 5 | click | name=nombre |  | 
    self.driver.find_element(By.NAME, "nombre").click()
    # 6 | click | css=.btn:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()
    # 7 | click | css=div:nth-child(10) h3 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(10) h3").click()
    # 8 | type | name=nombre | 3 | 
    self.driver.find_element(By.NAME, "nombre").send_keys("3")
    # 9 | click | name=nombre |  | 
    self.driver.find_element(By.NAME, "nombre").click()
    # 10 | type | name=nombre | 4 | 
    self.driver.find_element(By.NAME, "nombre").send_keys("4")
    # 11 | click | name=nombre |  | 
    self.driver.find_element(By.NAME, "nombre").click()
    # 12 | click | css=.btn:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()
    # 13 | click | css=div:nth-child(10) h3 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(10) h3").click()
    # 14 | click | css=h3 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "h3").click()
  
