# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestpolish():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testpolish(self):
    # Test name: test_polish
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("http://127.0.0.1:5000/")
    # 2 | setWindowSize | 1936x1176 |  | 
    self.driver.set_window_size(1936, 1176)
    # 3 | click | css=a:nth-child(2) > h2 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(2) > h2").click()
    # 4 | type | name=nombre1 | 1 | 
    self.driver.find_element(By.NAME, "nombre1").send_keys("1")
    # 5 | click | name=nombre1 |  | 
    self.driver.find_element(By.NAME, "nombre1").click()
    # 6 | type | name=nombre1 | 2 | 
    self.driver.find_element(By.NAME, "nombre1").send_keys("2")
    # 7 | click | name=nombre1 |  | 
    self.driver.find_element(By.NAME, "nombre1").click()
    # 8 | doubleClick | name=nombre1 |  | 
    element = self.driver.find_element(By.NAME, "nombre1")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 9 | type | name=nombre1 | 3 | 
    self.driver.find_element(By.NAME, "nombre1").send_keys("3")
    # 10 | click | name=nombre1 |  | 
    self.driver.find_element(By.NAME, "nombre1").click()
    # 11 | type | name=nombre1 | 4 | 
    self.driver.find_element(By.NAME, "nombre1").send_keys("4")
    # 12 | click | name=nombre1 |  | 
    self.driver.find_element(By.NAME, "nombre1").click()
    # 13 | doubleClick | name=nombre1 |  | 
    element = self.driver.find_element(By.NAME, "nombre1")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 14 | type | name=nombre2 | 0 | 
    self.driver.find_element(By.NAME, "nombre2").send_keys("0")
    # 15 | click | name=nombre2 |  | 
    self.driver.find_element(By.NAME, "nombre2").click()
    # 16 | click | name=nombre2 |  | 
    self.driver.find_element(By.NAME, "nombre2").click()
    # 17 | doubleClick | name=nombre2 |  | 
    element = self.driver.find_element(By.NAME, "nombre2")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 18 | click | name=nombre2 |  | 
    self.driver.find_element(By.NAME, "nombre2").click()
    # 19 | click | name=op |  | 
    self.driver.find_element(By.NAME, "op").click()
    # 20 | type | name=op | + | 
    self.driver.find_element(By.NAME, "op").send_keys("+")
    # 21 | click | id=btn |  | 
    self.driver.find_element(By.ID, "btn").click()
    # 22 | click | css=div:nth-child(10) h3 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(10) h3").click()
    # 23 | type | name=nombre1 | 1 | 
    self.driver.find_element(By.NAME, "nombre1").send_keys("1")
    # 24 | click | name=nombre1 |  | 
    self.driver.find_element(By.NAME, "nombre1").click()
    # 25 | click | name=nombre2 |  | 
    self.driver.find_element(By.NAME, "nombre2").click()
    # 26 | click | name=nombre1 |  | 
    self.driver.find_element(By.NAME, "nombre1").click()
    # 27 | type | name=nombre1 | 156 | 
    self.driver.find_element(By.NAME, "nombre1").send_keys("156")
    # 28 | click | name=nombre2 |  | 
    self.driver.find_element(By.NAME, "nombre2").click()
    # 29 | type | name=nombre2 | 41 | 
    self.driver.find_element(By.NAME, "nombre2").send_keys("41")
    # 30 | click | name=op |  | 
    self.driver.find_element(By.NAME, "op").click()
    # 31 | type | name=op | - | 
    self.driver.find_element(By.NAME, "op").send_keys("-")
    # 32 | click | id=btn |  | 
    self.driver.find_element(By.ID, "btn").click()
    # 33 | click | css=div:nth-child(10) h3 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(10) h3").click()
    # 34 | click | name=nombre1 |  | 
    self.driver.find_element(By.NAME, "nombre1").click()
    # 35 | type | name=nombre1 | 5000 | 
    self.driver.find_element(By.NAME, "nombre1").send_keys("5000")
    # 36 | click | name=nombre2 |  | 
    self.driver.find_element(By.NAME, "nombre2").click()
    # 37 | click | name=nombre1 |  | 
    self.driver.find_element(By.NAME, "nombre1").click()
    # 38 | type | name=nombre1 | 500 | 
    self.driver.find_element(By.NAME, "nombre1").send_keys("500")
    # 39 | click | name=nombre2 |  | 
    self.driver.find_element(By.NAME, "nombre2").click()
    # 40 | type | name=nombre2 | 2 | 
    self.driver.find_element(By.NAME, "nombre2").send_keys("2")
    # 41 | click | name=op |  | 
    self.driver.find_element(By.NAME, "op").click()
    # 42 | type | name=op | / | 
    self.driver.find_element(By.NAME, "op").send_keys("/")
    # 43 | click | id=btn |  | 
    self.driver.find_element(By.ID, "btn").click()
    # 44 | click | css=div:nth-child(10) h3 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(10) h3").click()
    # 45 | click | name=nombre1 |  | 
    self.driver.find_element(By.NAME, "nombre1").click()
    # 46 | type | name=nombre1 | 50 | 
    self.driver.find_element(By.NAME, "nombre1").send_keys("50")
    # 47 | click | name=nombre2 |  | 
    self.driver.find_element(By.NAME, "nombre2").click()
    # 48 | type | name=nombre2 | 0 | 
    self.driver.find_element(By.NAME, "nombre2").send_keys("0")
    # 49 | click | name=op |  | 
    self.driver.find_element(By.NAME, "op").click()
    # 50 | type | name=op | / | 
    self.driver.find_element(By.NAME, "op").send_keys("/")
    # 51 | click | id=btn |  | 
    self.driver.find_element(By.ID, "btn").click()
  
