# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestwspliter():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testwspliter(self):
    # Test name: test_wspliter
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("http://127.0.0.1:5000/")
    # 2 | setWindowSize | 1936x1176 |  | 
    self.driver.set_window_size(1936, 1176)
    # 3 | click | css=a:nth-child(3) > h2 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(3) > h2").click()
    # 4 | click | name=phrase |  | 
    self.driver.find_element(By.NAME, "phrase").click()
    # 5 | click | css=h5 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "h5").click()
    # 6 | type | name=phrase | Cette application a pour objectif de conserver les  | 
    self.driver.find_element(By.NAME, "phrase").send_keys("Cette application a pour objectif de conserver les ")
    # 7 | click | css=.text-center:nth-child(6) > .btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(6) > .btn").click()
    # 8 | click | css=div:nth-child(10) h3 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(10) h3").click()
    # 9 | type | name=phrase | Le Lorem Ipsum est simplement du faux texte employé | 
    self.driver.find_element(By.NAME, "phrase").send_keys("Le Lorem Ipsum est simplement du faux texte employé")
    # 10 | click | css=.text-center:nth-child(6) > .btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(6) > .btn").click()
    # 11 | click | css=div:nth-child(6) h3 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(6) h3").click()
    # 12 | type | name=phrase | Le Lorem Ipsum est simplement du faux texte employé | 
    self.driver.find_element(By.NAME, "phrase").send_keys("Le Lorem Ipsum est simplement du faux texte employé")
    # 13 | click | css=.text-center:nth-child(6) > .btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(6) > .btn").click()
    # 14 | click | css=div:nth-child(9) h3 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(9) h3").click()
    # 15 | click | css=a:nth-child(3) > h2 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(3) > h2").click()
    # 16 | type | name=phrase | Le Lorem Ipsum est simplement du faux texte employé | 
    self.driver.find_element(By.NAME, "phrase").send_keys("Le Lorem Ipsum est simplement du faux texte employé")
    # 17 | click | css=.text-center:nth-child(6) > .btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(6) > .btn").click()
    # 18 | click | css=div:nth-child(10) h3 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(10) h3").click()
    # 19 | type | name=phrase | Le Lorem Ipsum est simplement du faux texte employé | 
    self.driver.find_element(By.NAME, "phrase").send_keys("Le Lorem Ipsum est simplement du faux texte employé")
    # 20 | click | css=.text-center:nth-child(6) > .btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(6) > .btn").click()
    # 21 | click | css=div:nth-child(6) h3 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(6) h3").click()
    # 22 | click | css=h3 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "h3").click()
    # 23 | click | css=a:nth-child(4) > h2 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4) > h2").click()
    # 24 | click | css=h3 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "h3").click()
    # 25 | click | css=a:nth-child(3) > h2 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(3) > h2").click()
    # 26 | type | name=phrase | Le Lorem Ipsum est simplement du faux texte employé | 
    self.driver.find_element(By.NAME, "phrase").send_keys("Le Lorem Ipsum est simplement du faux texte employé")
    # 27 | click | css=.text-center:nth-child(6) > .btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(6) > .btn").click()
    # 28 | click | css=div:nth-child(10) h3 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(10) h3").click()
    # 29 | click | css=.text-center:nth-child(6) > .btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(6) > .btn").click()
    # 30 | click | css=div:nth-child(10) h3 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(10) h3").click()
    # 31 | type | name=phrase | Le Lorem Ipsum est simplement du faux texte employé | 
    self.driver.find_element(By.NAME, "phrase").send_keys("Le Lorem Ipsum est simplement du faux texte employé")
    # 32 | click | css=.text-center:nth-child(6) > .btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(6) > .btn").click()
    # 33 | close |  |  | 
    self.driver.close()
  
